### ISSUE TITLE
could you add me on discord?

### ISSUE THREAD

**Issue by 9tro** [xAffan/discord-token-invite-joiner#1]
the title says it all. just need to ask a couple questions, not about this, but about how you got the gen to work. you don't have to give it to me, i'm just asking for a little help lol

thanks

**Comment by 9tro** [comment]
lost.#1354

**Comment by cChimney** [comment]
yo can u add me too cChimney#5516 thanks mate

**Comment by cChimney** [comment]
add me, lost and affan

**Comment by cChimney** [comment]
cChimney#0694

**Comment by cChimney** [comment]
#0694

**Comment by xAffan** [comment]
My discord is xAffan#7302
